stages:
  - build
  - release

smdc_portal_build_linux:
  stage: build
  image: ubuntu:22.04
  # image: rust:bookworm
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/'
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^portal-v/'
  script:
    - echo "Building the project..."
    - apt update
    - apt install unzip libdbus-1-dev pkg-config zlib1g libevent-dev libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev librsvg2-dev libfuse2 libappindicator3-dev libwebkit2gtk-4.1-dev libffi-dev patchelf -y
    - curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh; rm -f /usr/share/keyrings/nodesource.gpg; chmod 500 nsolid_setup_deb.sh; ./nsolid_setup_deb.sh 23; apt-get install nodejs -y; rm -f ./nsolid_setup_deb.sh
    - curl -fsSL https://bun.sh/install | bash
    - curl https://sh.rustup.rs --output ./rust.sh;chmod +x ./rust.sh;./rust.sh -y;rm ./rust.sh
    - export PATH="$HOME/.bun/bin:$PATH"
    - bun install @tauri-apps/cli-linux-x64-gnu --force
    - export PATH="$HOME/.cargo/bin:$PATH"
    - bun run build:bun
    - mkdir -p exe
    - cp ./src-tauri/target/release/smdc_portal ./exe/smdc_portal
  artifacts:
    paths:
      - exe/smdc_portal

smdc_portal_build_windows:
  stage: build
  image: docker:27.4.1-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - name: docker:27.4.1-dind
      alias: docker
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/'
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^portal-v/'
  before_script:
    - until docker info; do sleep 1; done
  script:
    - echo "Building the project..."
    - apk update
    - apk add unzip curl wget
    - curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
    - export PATH="$HOME/.local/bin:$PATH"
    - cd .ci
    - dagger call windows --src=../ export --path="$(dirname $(pwd))/exe/smdc_portal.exe"
  artifacts:
    paths:
      - exe/smdc_portal.exe

smdc_portal_upload_package:
  stage: .post
  image: curlimages/curl:latest
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/'
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^portal-v/'
  script:
    - 'curl -k --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file exe/smdc_portal "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/smdc_portal/${CI_COMMIT_TAG}/smdc_portal"'
    - 'curl -k --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file exe/smdc_portal.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/smdc_portal/${CI_COMMIT_TAG}/smdc_portal.exe"'

smdc_portal_release_job:
  stage: .post
  image: curlimages/curl:latest
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/'
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^portal-v/'
  script: |
    echo "Creating a release...";
    curl -k --header 'Content-Type: application/json' --header "JOB-TOKEN: $CI_JOB_TOKEN" \
     --data "{ \"name\": \"Release $CI_COMMIT_TAG\", \"tag_name\": \"$CI_COMMIT_TAG\", \"ref\": \"$CI_COMMIT_SHA\", \"description\": \"Release for tag $CI_COMMIT_TAG\", \"assets\": { \"links\": [{ \"name\": \"SMDC-Portal\", \"url\": \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/smdc_portal/${CI_COMMIT_TAG}/smdc_portal\" },{ \"name\": \"SMDC-Portal.exe\", \"url\": \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/smdc_portal/${CI_COMMIT_TAG}/smdc_portal.exe\" }] } }" \
     --request POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases";
