[env]

[hooks]

[settings]
auto_install = false
activate_aggressive = true
aqua.cosign = false
aqua.slsa = false
experimental = true
fetch_remote_versions_cache = "1d"
idiomatic_version_file_enable_tools = ["node"]
jobs = 100
lockfile = false
node.gpg_verify = false
python.compile = false
quiet = false
task_output = "quiet"
unix_default_inline_shell_args = "bash -uc"
windows_default_file_shell_args = "pwsh -c"

[tools]
biome = 'latest'
bun = "latest"
dagger = 'latest'
deno = 'latest'
docker-cli = 'latest'
node = "latest"
powershell-core = 'latest'
rust = 'latest'

[vars]

[tasks."test"]
run = """
cargo test --manifest-path src-tauri/Cargo.toml
"""

[tasks."build"]
run = """
bun install && bun run build:bun:debug
"""

[tasks."start"]
run = """
bun run start
"""

[tasks."install"]
run = """
bun install
"""

[tasks."qwik"]
run = """
bun install && bun run qwik:build
"""

[tasks."release"]
run = """
bun run build:bun
"""

[tasks."debug"]
run = """
bun run build:bun:debug
"""

[tasks."fmt"]
run = """
bun run fmt
"""

[tasks."clean"]
shell = """
{% if os_family() == "windows" %}pwsh -c{% else %}bash -c{% endif %}
"""
run = """
bun run clean
"""

[tasks."docker"]
run = """
{% set sudo = "" %}{% if os_family() != "windows" %}{% set sudo = "sudo " %}{% endif %}
docker build -t tauri --output type=local,dest=./out/ .
"""

[tasks."upgrade"]
run = """
bun run update
"""

[tasks."dagger_windows"]
run = """
{% set output_path = cwd ~ "/out/smdc_portal.exe" %}
{% if os_family() == "windows" %}
cd .ci && pwsh -c Start-Process 'dagger' -ArgumentList 'call windows --src=../ export --path={{ output_path }}' -Wait -NoNewWindow
{% else %}
cd .ci && dagger call windows --src=../ export --path={{ output_path }}
{% endif %}
"""

[tasks."dagger_linux"]
run = """
{% set output_path = cwd ~ "/out/smdc_portal" %}
{% if os_family() == "windows" %}
cd .ci && pwsh -c Start-Process 'dagger' -ArgumentList 'call linux --src=../ export --path={{ output_path }}' -Wait -NoNewWindow
{% else %}
cd .ci && dagger call linux --src=../ export --path={{ output_path }}
{% endif %}
"""

[tasks."code_server"]
run = """
{% set sudo = "" %}{% if os_family() != "windows" %}{% set sudo = "sudo " %}{% endif %}
{% set workspace = "" %}{% if os_family() == "windows" %}{% set workspace = cwd %}{% else %}{% set workspace = "/workspace/smdc_portal" %}{% endif %}
{{ sudo }} docker run -v /var/run/docker.sock:/var/run/docker.sock -v {{cwd}}:{{ workspace }} --name=code_server -p 443:443 -d matthewhambright/code_server:latest || echo "Container Exists"
"""

[tasks."code_server_use"]
run = """
{% set sudo = "" %}{% if os_family() != "windows" %}{% set sudo = "sudo " %}{% endif %}
{{ sudo }} docker exec -it code_server zsh
"""

[tasks."code_server_delete"]
run = """
{% set sudo = "" %}{% if os_family() != "windows" %}{% set sudo = "sudo " %}{% endif %}
{{ sudo }} docker rm -f code_server
"""

[tasks."codeberg_runners_up"]
run = """
{% set sudo = "" %}{% if os_family() != "windows" %}{% set sudo = "sudo " %}{% endif %}
cd ./.ci/codeberg && {{ sudo }} docker compose --env-file .env up -d
"""

[tasks."codeberg_runners_down"]
run = """
{% set sudo = "" %}{% if os_family() != "windows" %}{% set sudo = "sudo " %}{% endif %}
cd ./.ci/codeberg && {{ sudo }} docker compose down
"""

[tasks."gitea_runners_up"]
run = """
{% set sudo = "" %}{% if os_family() != "windows" %}{% set sudo = "sudo " %}{% endif %}
cd ./.ci/gitea && {{ sudo }} docker compose --env-file .env up -d
"""

[tasks."gitea_runners_down"]
run = """
{% set sudo = "" %}{% if os_family() != "windows" %}{% set sudo = "sudo " %}{% endif %}
cd ./.ci/gitea && {{ sudo }} docker compose down
"""