name: smdc_portal_tests
on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust:
    name: Run Cargo Tests
    runs-on: ubuntu-24.04
   
    steps:
      - uses: actions/checkout@v4
     
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
     
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
     
      - name: Install Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            libjavascriptcoregtk-4.1-dev
     
      - name: Run tests in root workspace
        run: cargo test --manifest-path src-tauri/Cargo.toml

  bun:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Install dependencies
        run: bun install
        
      - name: Install Playwright Browsers
        run: bun x playwright install --with-deps
        
      - name: Run Playwright tests
        run: bun run test.e2e